apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nxrm-deployment-nexus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: nxrm-deployment-nexus
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
